### ISSUE TITLE
env-local didn't work

### ISSUE THREAD

**Issue by 1UnboundedSentience** [enreeco/sf-git#2]
I had to install dotenv in npm and create my own separate .env file instead of using the .env-local provided

**Comment by 1UnboundedSentience** [comment]
This is a relatively small issue.  A bigger question is how to make this fetch from multiple salesforce orgs?

**Comment by enreeco** [comment]
Hi @1UnboundedSentience ,
the .env-local file is only an example .env file, you should rename it in .env and use you preferred execution package, as you did.
If you need multiple ORGs backup you need multiple Heroku instances running different instances (this is how I'm actually backing up my orgs).
