### ISSUE TITLE
No support for test orgs?

### ISSUE THREAD

**Issue by 1UnboundedSentience** [enreeco/sf-git#3]
I got this to work for a production org, but I don't see a place to specify if the org is a test org (access through test.salesforce.com).  Does this app work with Salesforce test orgs?

**Comment by enreeco** [comment]
I cannot believe I forgot to do this...Thanks for pointing out.
I'll add a new env process variable, in the meanwhile you can change line 54 of file **sf-git.js** with:
```javascript
sfConnection : (new jsforce.Connection({loginUrl: 'https://test.salesforce.com'})),
```
