### ISSUE TITLE
Feature Request: REPO_BRANCH

### ISSUE THREAD

**Issue by mickster04** [enreeco/sf-git#7]
Is it possible to enable to the use of a specific branch of a repo? We would use it to back up a sandbox as well as the prod org to be able to see differences between the two etc. I would only expect to back up one org at a time, but this would be a useful feature for me.

**Comment by mickster04** [comment]
This would also use the SF_LOGIN_URL variable (which isn't documented btw)

**Comment by enreeco** [comment]
Documentation updated
